title: Štíhle mesto Prešov

description: >
 "Prešov ako Lean city. Koncept pre zodpovedne spravované mesto"
url: "https://presov.imcontec.eu"
lang: sk_SK

show_excerpts: true

plugins:
  - jekyll-paginate-v2
  - jekyll-remote-theme

remote_theme: daattali/beautiful-jekyll@6.0.1
